# Generated by Django 2.2 on 2023-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230531_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
